### PR TITLE
Deployment on GKE

### PR DESCRIPTION
**Pull request by dsever**
Small contribution, simple example of deployment on top of the GKE

### CODE REVIEW

**Comment by mtesauro** [comment]
@dsever This is great. Thanks for sharing. Let me know when this is ready and I will happily merge it if you don't have access.

**Comment by dsever** [comment]
I have rights, but wanted to see your feedback if something needs to be reworked

**Comment by mtesauro** [comment]
@dsever Roger that. It's been so long since we setup the permissions, I wasn't sure about the ability to merge.

Thanks again for this - hopefully, you'll get some feedback. :+1:

**Comment by alles-klar** [comment]
@dsever I haven't worked with GKE yet. In general it look good. 

Since it is only about docs, do we want to integration such kind of documentation to our official version. Maybe a chapter with community docs or similar? When users search for these information it would be much easier to find there than here.

**Pull request merged**
